//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Sharebits.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResxFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResxFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FYP_Sharebits.Resources.ResxFile", typeof(ResxFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        public static string btn_accept {
            get {
                return ResourceManager.GetString("btn_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Plan to Student.
        /// </summary>
        public static string btn_assignPlan {
            get {
                return ResourceManager.GetString("btn_assignPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a coach.
        /// </summary>
        public static string btn_beCoach {
            get {
                return ResourceManager.GetString("btn_beCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        public static string btn_chat {
            get {
                return ResourceManager.GetString("btn_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check recommended plan(s) from coach.
        /// </summary>
        public static string btn_checkNewRec {
            get {
                return ResourceManager.GetString("btn_checkNewRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Coaching Request.
        /// </summary>
        public static string btn_checkRequest {
            get {
                return ResourceManager.GetString("btn_checkRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach List.
        /// </summary>
        public static string btn_coachList {
            get {
                return ResourceManager.GetString("btn_coachList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLINE.
        /// </summary>
        public static string btn_decline {
            get {
                return ResourceManager.GetString("btn_decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        public static string btn_Enter {
            get {
                return ResourceManager.GetString("btn_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find coach.
        /// </summary>
        public static string btn_findCoach {
            get {
                return ResourceManager.GetString("btn_findCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Student.
        /// </summary>
        public static string btn_my_student {
            get {
                return ResourceManager.GetString("btn_my_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string btn_no {
            get {
                return ResourceManager.GetString("btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEED.
        /// </summary>
        public static string btn_proceed {
            get {
                return ResourceManager.GetString("btn_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull plans from server.
        /// </summary>
        public static string btn_pullPlan {
            get {
                return ResourceManager.GetString("btn_pullPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push plans to server.
        /// </summary>
        public static string btn_pushPlans {
            get {
                return ResourceManager.GetString("btn_pushPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string btn_remove {
            get {
                return ResourceManager.GetString("btn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string btn_Signup {
            get {
                return ResourceManager.GetString("btn_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student List.
        /// </summary>
        public static string btn_studentList {
            get {
                return ResourceManager.GetString("btn_studentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View shared plans.
        /// </summary>
        public static string btn_viewShare {
            get {
                return ResourceManager.GetString("btn_viewShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string btn_yes {
            get {
                return ResourceManager.GetString("btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He/She is coaching you already!.
        /// </summary>
        public static string err_coachAlready {
            get {
                return ResourceManager.GetString("err_coachAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string err_confirm {
            get {
                return ResourceManager.GetString("err_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting request from database..
        /// </summary>
        public static string err_deleteRequest {
            get {
                return ResourceManager.GetString("err_deleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while inserting row to Students..
        /// </summary>
        public static string err_insertStudent {
            get {
                return ResourceManager.GetString("err_insertStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of work done cannot be empty in this case!.
        /// </summary>
        public static string err_InvalidAmt {
            get {
                return ResourceManager.GetString("err_InvalidAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 plan item has to be added!.
        /// </summary>
        public static string err_NoPlanItem {
            get {
                return ResourceManager.GetString("err_NoPlanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no plan in the server from you!.
        /// </summary>
        public static string err_noPlanPull {
            get {
                return ResourceManager.GetString("err_noPlanPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All plans have been pushed to server already!.
        /// </summary>
        public static string err_noPlanPush {
            get {
                return ResourceManager.GetString("err_noPlanPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan name cannot be empty!.
        /// </summary>
        public static string err_NullPlanName {
            get {
                return ResourceManager.GetString("err_NullPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent a request to him/her already!.
        /// </summary>
        public static string err_reqAlready {
            get {
                return ResourceManager.GetString("err_reqAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while sending coaching request..
        /// </summary>
        public static string err_sendCoachReq {
            get {
                return ResourceManager.GetString("err_sendCoachReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Category.
        /// </summary>
        public static string lbl_ActCategory {
            get {
                return ResourceManager.GetString("lbl_ActCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patterns.
        /// </summary>
        public static string lbl_ActPattern {
            get {
                return ResourceManager.GetString("lbl_ActPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string lbl_ActType {
            get {
                return ResourceManager.GetString("lbl_ActType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string lbl_birthday {
            get {
                return ResourceManager.GetString("lbl_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Time.
        /// </summary>
        public static string lbl_commentDate {
            get {
                return ResourceManager.GetString("lbl_commentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string lbl_confirm_password {
            get {
                return ResourceManager.GetString("lbl_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of work done.
        /// </summary>
        public static string lbl_Done {
            get {
                return ResourceManager.GetString("lbl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lbl_female {
            get {
                return ResourceManager.GetString("lbl_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lbl_gender {
            get {
                return ResourceManager.GetString("lbl_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lbl_gender_female {
            get {
                return ResourceManager.GetString("lbl_gender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lbl_gender_male {
            get {
                return ResourceManager.GetString("lbl_gender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string lbl_height {
            get {
                return ResourceManager.GetString("lbl_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished:.
        /// </summary>
        public static string lbl_isDone {
            get {
                return ResourceManager.GetString("lbl_isDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lbl_male {
            get {
                return ResourceManager.GetString("lbl_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of newly done.
        /// </summary>
        public static string lbl_NewDone {
            get {
                return ResourceManager.GetString("lbl_NewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Item&apos;s Name.
        /// </summary>
        public static string lbl_PIName {
            get {
                return ResourceManager.GetString("lbl_PIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name.
        /// </summary>
        public static string lbl_PlanName {
            get {
                return ResourceManager.GetString("lbl_PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Type.
        /// </summary>
        public static string lbl_PlanType {
            get {
                return ResourceManager.GetString("lbl_PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string lbl_progress {
            get {
                return ResourceManager.GetString("lbl_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string lbl_student {
            get {
                return ResourceManager.GetString("lbl_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lbl_username {
            get {
                return ResourceManager.GetString("lbl_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string lbl_weight {
            get {
                return ResourceManager.GetString("lbl_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity amount.
        /// </summary>
        public static string lbl_workAmt {
            get {
                return ResourceManager.GetString("lbl_workAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach.
        /// </summary>
        public static string lblCoach {
            get {
                return ResourceManager.GetString("lblCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit.
        /// </summary>
        public static string lblHabit {
            get {
                return ResourceManager.GetString("lblHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string lblSocial {
            get {
                return ResourceManager.GetString("lblSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching Request Accepted.
        /// </summary>
        public static string msg_acceptRequest {
            get {
                return ResourceManager.GetString("msg_acceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept this coaching request?.
        /// </summary>
        public static string msg_acceptStudent {
            get {
                return ResourceManager.GetString("msg_acceptStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have become his/her coach successfully! You may check it in your student list!.
        /// </summary>
        public static string msg_addCoachSucc {
            get {
                return ResourceManager.GetString("msg_addCoachSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming coach successfully!.
        /// </summary>
        public static string msg_beCoachSucc {
            get {
                return ResourceManager.GetString("msg_beCoachSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to take the responsibility of coaching people to build a good habit with a feasible plan..
        /// </summary>
        public static string msg_coachResponsibility {
            get {
                return ResourceManager.GetString("msg_coachResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string msg_confirm {
            get {
                return ResourceManager.GetString("msg_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept this plan or decline it?.
        /// </summary>
        public static string msg_confirmCoachPlan {
            get {
                return ResourceManager.GetString("msg_confirmCoachPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to accept his/her request?.
        /// </summary>
        public static string msg_confirmCoachReq {
            get {
                return ResourceManager.GetString("msg_confirmCoachReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished weitting comment and want to post it?.
        /// </summary>
        public static string msg_confirmComment {
            get {
                return ResourceManager.GetString("msg_confirmComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want him/her to be your coach?.
        /// </summary>
        public static string msg_confirmSendReq {
            get {
                return ResourceManager.GetString("msg_confirmSendReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to share this plan to the public?.
        /// </summary>
        public static string msg_confirmSharePlan {
            get {
                return ResourceManager.GetString("msg_confirmSharePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined the assigned plan successfully!.
        /// </summary>
        public static string msg_DeclinePlanSucc {
            get {
                return ResourceManager.GetString("msg_DeclinePlanSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching Request Declined.
        /// </summary>
        public static string msg_declineRequest {
            get {
                return ResourceManager.GetString("msg_declineRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the informations..
        /// </summary>
        public static string msg_info_empty {
            get {
                return ResourceManager.GetString("msg_info_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        public static string msg_InvalidAction {
            get {
                return ResourceManager.GetString("msg_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have achieved today&apos;s goal!.
        /// </summary>
        public static string msg_itemFin {
            get {
                return ResourceManager.GetString("msg_itemFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation!.
        /// </summary>
        public static string msg_ItemFin_title {
            get {
                return ResourceManager.GetString("msg_ItemFin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password!.
        /// </summary>
        public static string msg_Login_Fail {
            get {
                return ResourceManager.GetString("msg_Login_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email and password to login..
        /// </summary>
        public static string msg_LoginEmpty {
            get {
                return ResourceManager.GetString("msg_LoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout failed! Please try it later..
        /// </summary>
        public static string msg_Logout_Fail {
            get {
                return ResourceManager.GetString("msg_Logout_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This habit plan has not started yet..
        /// </summary>
        public static string msg_NotStarted {
            get {
                return ResourceManager.GetString("msg_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed! Please try it later..
        /// </summary>
        public static string msg_operation_fail {
            get {
                return ResourceManager.GetString("msg_operation_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment successfully!.
        /// </summary>
        public static string msg_postCommentSucc {
            get {
                return ResourceManager.GetString("msg_postCommentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling plans from server successfully!.
        /// </summary>
        public static string msg_pullPlanSucc {
            get {
                return ResourceManager.GetString("msg_pullPlanSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing all unpushed plans to the server?.
        /// </summary>
        public static string msg_pushPlans {
            get {
                return ResourceManager.GetString("msg_pushPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing plans to server successfully!.
        /// </summary>
        public static string msg_pushPlanSucc {
            get {
                return ResourceManager.GetString("msg_pushPlanSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two passwords are not the same..
        /// </summary>
        public static string msg_pwd_diff {
            get {
                return ResourceManager.GetString("msg_pwd_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string msg_rusure {
            get {
                return ResourceManager.GetString("msg_rusure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching request sent!.
        /// </summary>
        public static string msg_sendCoachReq {
            get {
                return ResourceManager.GetString("msg_sendCoachReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists! Please use another email..
        /// </summary>
        public static string msg_signup_repeat_user {
            get {
                return ResourceManager.GetString("msg_signup_repeat_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created an account successfully!.
        /// </summary>
        public static string msg_signup_succ {
            get {
                return ResourceManager.GetString("msg_signup_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string msg_Success {
            get {
                return ResourceManager.GetString("msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added a new habit plan successfully!.
        /// </summary>
        public static string msg_SuccNewPlan {
            get {
                return ResourceManager.GetString("msg_SuccNewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string msg_succShare {
            get {
                return ResourceManager.GetString("msg_succShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to use this function!.
        /// </summary>
        public static string msg_Unauthenticated {
            get {
                return ResourceManager.GetString("msg_Unauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred..
        /// </summary>
        public static string msg_unknownErr {
            get {
                return ResourceManager.GetString("msg_unknownErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have updated the amount of work done! Keep going and try to achieve today&apos;s target!.
        /// </summary>
        public static string msg_UpdateRecSucc {
            get {
                return ResourceManager.GetString("msg_UpdateRecSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update record successfully.
        /// </summary>
        public static string msg_UpdateRecSucc_title {
            get {
                return ResourceManager.GetString("msg_UpdateRecSucc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run ... meter per day.
        /// </summary>
        public static string pat_Run_Dist_meter {
            get {
                return ResourceManager.GetString("pat_Run_Dist_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run for ... hours per day.
        /// </summary>
        public static string pat_Run_Dur_hours {
            get {
                return ResourceManager.GetString("pat_Run_Dur_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run for ... minutes per day.
        /// </summary>
        public static string pat_Run_Dur_minutes {
            get {
                return ResourceManager.GetString("pat_Run_Dur_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk ... meter per day.
        /// </summary>
        public static string pat_Walk_Dist_meter {
            get {
                return ResourceManager.GetString("pat_Walk_Dist_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk for ... hours per day.
        /// </summary>
        public static string pat_Walk_Dur_hours {
            get {
                return ResourceManager.GetString("pat_Walk_Dur_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk for ... minutes per day.
        /// </summary>
        public static string pat_Walk_Dur_minutes {
            get {
                return ResourceManager.GetString("pat_Walk_Dur_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk ... steps per day.
        /// </summary>
        public static string pat_Walk_Steps {
            get {
                return ResourceManager.GetString("pat_Walk_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string pker_Challenge {
            get {
                return ResourceManager.GetString("pker_Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string pker_Dist {
            get {
                return ResourceManager.GetString("pker_Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string pker_Dur {
            get {
                return ResourceManager.GetString("pker_Dur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string pker_Normal {
            get {
                return ResourceManager.GetString("pker_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string pker_Run {
            get {
                return ResourceManager.GetString("pker_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string pker_Steps {
            get {
                return ResourceManager.GetString("pker_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string pker_Times {
            get {
                return ResourceManager.GetString("pker_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking.
        /// </summary>
        public static string pker_Walk {
            get {
                return ResourceManager.GetString("pker_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done or not.
        /// </summary>
        public static string pker_YesNo {
            get {
                return ResourceManager.GetString("pker_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string str_error {
            get {
                return ResourceManager.GetString("str_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string tbi_addComment {
            get {
                return ResourceManager.GetString("tbi_addComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string tbi_AddItem {
            get {
                return ResourceManager.GetString("tbi_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a plan.
        /// </summary>
        public static string tbi_assignPlan {
            get {
                return ResourceManager.GetString("tbi_assignPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string tbi_clone {
            get {
                return ResourceManager.GetString("tbi_clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string tbi_comment {
            get {
                return ResourceManager.GetString("tbi_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string tbi_post {
            get {
                return ResourceManager.GetString("tbi_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string tbi_records {
            get {
                return ResourceManager.GetString("tbi_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string tbi_response {
            get {
                return ResourceManager.GetString("tbi_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string tbi_sendReq {
            get {
                return ResourceManager.GetString("tbi_sendReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string tbi_share {
            get {
                return ResourceManager.GetString("tbi_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string tbi_user {
            get {
                return ResourceManager.GetString("tbi_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter comment below!.
        /// </summary>
        public static string title_comment {
            get {
                return ResourceManager.GetString("title_comment", resourceCulture);
            }
        }
    }
}
