//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Sharebits.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResxFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResxFile() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FYP_Sharebits.Resources.ResxFile", typeof(ResxFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 ADD 的當地語系化字串。
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CHAT 的當地語系化字串。
        /// </summary>
        public static string btn_chat {
            get {
                return ResourceManager.GetString("btn_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Check recommended plan(s) from coach 的當地語系化字串。
        /// </summary>
        public static string btn_checkNewRec {
            get {
                return ResourceManager.GetString("btn_checkNewRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coach List 的當地語系化字串。
        /// </summary>
        public static string btn_coachList {
            get {
                return ResourceManager.GetString("btn_coachList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ENTER 的當地語系化字串。
        /// </summary>
        public static string btn_Enter {
            get {
                return ResourceManager.GetString("btn_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Find coach 的當地語系化字串。
        /// </summary>
        public static string btn_findCoach {
            get {
                return ResourceManager.GetString("btn_findCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout 的當地語系化字串。
        /// </summary>
        public static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PROCEED 的當地語系化字串。
        /// </summary>
        public static string btn_proceed {
            get {
                return ResourceManager.GetString("btn_proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 REMOVE 的當地語系化字串。
        /// </summary>
        public static string btn_remove {
            get {
                return ResourceManager.GetString("btn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Signup 的當地語系化字串。
        /// </summary>
        public static string btn_Signup {
            get {
                return ResourceManager.GetString("btn_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CONFIRM 的當地語系化字串。
        /// </summary>
        public static string err_confirm {
            get {
                return ResourceManager.GetString("err_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The amount of work done cannot be empty in this case! 的當地語系化字串。
        /// </summary>
        public static string err_InvalidAmt {
            get {
                return ResourceManager.GetString("err_InvalidAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 At least 1 plan item has to be added! 的當地語系化字串。
        /// </summary>
        public static string err_NoPlanItem {
            get {
                return ResourceManager.GetString("err_NoPlanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plan name cannot be empty! 的當地語系化字串。
        /// </summary>
        public static string err_NullPlanName {
            get {
                return ResourceManager.GetString("err_NullPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Activity Category 的當地語系化字串。
        /// </summary>
        public static string lbl_ActCategory {
            get {
                return ResourceManager.GetString("lbl_ActCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Patterns 的當地語系化字串。
        /// </summary>
        public static string lbl_ActPattern {
            get {
                return ResourceManager.GetString("lbl_ActPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measurement 的當地語系化字串。
        /// </summary>
        public static string lbl_ActType {
            get {
                return ResourceManager.GetString("lbl_ActType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm password 的當地語系化字串。
        /// </summary>
        public static string lbl_confirm_password {
            get {
                return ResourceManager.GetString("lbl_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount of work done 的當地語系化字串。
        /// </summary>
        public static string lbl_Done {
            get {
                return ResourceManager.GetString("lbl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 End Date 的當地語系化字串。
        /// </summary>
        public static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gender 的當地語系化字串。
        /// </summary>
        public static string lbl_gender {
            get {
                return ResourceManager.GetString("lbl_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Female 的當地語系化字串。
        /// </summary>
        public static string lbl_gender_female {
            get {
                return ResourceManager.GetString("lbl_gender_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Male 的當地語系化字串。
        /// </summary>
        public static string lbl_gender_male {
            get {
                return ResourceManager.GetString("lbl_gender_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Height 的當地語系化字串。
        /// </summary>
        public static string lbl_height {
            get {
                return ResourceManager.GetString("lbl_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Amount of newly done 的當地語系化字串。
        /// </summary>
        public static string lbl_NewDone {
            get {
                return ResourceManager.GetString("lbl_NewDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plan Item&apos;s Name 的當地語系化字串。
        /// </summary>
        public static string lbl_PIName {
            get {
                return ResourceManager.GetString("lbl_PIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plan Name 的當地語系化字串。
        /// </summary>
        public static string lbl_PlanName {
            get {
                return ResourceManager.GetString("lbl_PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Plan Type 的當地語系化字串。
        /// </summary>
        public static string lbl_PlanType {
            get {
                return ResourceManager.GetString("lbl_PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Date 的當地語系化字串。
        /// </summary>
        public static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Username 的當地語系化字串。
        /// </summary>
        public static string lbl_username {
            get {
                return ResourceManager.GetString("lbl_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weight 的當地語系化字串。
        /// </summary>
        public static string lbl_weight {
            get {
                return ResourceManager.GetString("lbl_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Activity amount 的當地語系化字串。
        /// </summary>
        public static string lbl_workAmt {
            get {
                return ResourceManager.GetString("lbl_workAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Coach 的當地語系化字串。
        /// </summary>
        public static string lblCoach {
            get {
                return ResourceManager.GetString("lblCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Habit 的當地語系化字串。
        /// </summary>
        public static string lblHabit {
            get {
                return ResourceManager.GetString("lblHabit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile 的當地語系化字串。
        /// </summary>
        public static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Social 的當地語系化字串。
        /// </summary>
        public static string lblSocial {
            get {
                return ResourceManager.GetString("lblSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill in all the informations. 的當地語系化字串。
        /// </summary>
        public static string msg_info_empty {
            get {
                return ResourceManager.GetString("msg_info_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Action 的當地語系化字串。
        /// </summary>
        public static string msg_InvalidAction {
            get {
                return ResourceManager.GetString("msg_InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have achieved today&apos;s goal! 的當地語系化字串。
        /// </summary>
        public static string msg_itemFin {
            get {
                return ResourceManager.GetString("msg_itemFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Congratulation! 的當地語系化字串。
        /// </summary>
        public static string msg_ItemFin_title {
            get {
                return ResourceManager.GetString("msg_ItemFin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incorrect email or password! 的當地語系化字串。
        /// </summary>
        public static string msg_Login_Fail {
            get {
                return ResourceManager.GetString("msg_Login_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your email and password to login. 的當地語系化字串。
        /// </summary>
        public static string msg_LoginEmpty {
            get {
                return ResourceManager.GetString("msg_LoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout failed! Please try it later. 的當地語系化字串。
        /// </summary>
        public static string msg_Logout_Fail {
            get {
                return ResourceManager.GetString("msg_Logout_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This habit plan has not started yet. 的當地語系化字串。
        /// </summary>
        public static string msg_NotStarted {
            get {
                return ResourceManager.GetString("msg_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation failed! Please try it later. 的當地語系化字串。
        /// </summary>
        public static string msg_operation_fail {
            get {
                return ResourceManager.GetString("msg_operation_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Two passwords are not the same. 的當地語系化字串。
        /// </summary>
        public static string msg_pwd_diff {
            get {
                return ResourceManager.GetString("msg_pwd_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User already exists! Please use another email. 的當地語系化字串。
        /// </summary>
        public static string msg_signup_repeat_user {
            get {
                return ResourceManager.GetString("msg_signup_repeat_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have created an account successfully! 的當地語系化字串。
        /// </summary>
        public static string msg_signup_succ {
            get {
                return ResourceManager.GetString("msg_signup_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        public static string msg_Success {
            get {
                return ResourceManager.GetString("msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Added a new habit plan successfully! 的當地語系化字串。
        /// </summary>
        public static string msg_SuccNewPlan {
            get {
                return ResourceManager.GetString("msg_SuccNewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please login to use this function! 的當地語系化字串。
        /// </summary>
        public static string msg_Unauthenticated {
            get {
                return ResourceManager.GetString("msg_Unauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have updated the amount of work done! Keep going and try to achieve today&apos;s target! 的當地語系化字串。
        /// </summary>
        public static string msg_UpdateRecSucc {
            get {
                return ResourceManager.GetString("msg_UpdateRecSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update record successfully 的當地語系化字串。
        /// </summary>
        public static string msg_UpdateRecSucc_title {
            get {
                return ResourceManager.GetString("msg_UpdateRecSucc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run ... meter per day 的當地語系化字串。
        /// </summary>
        public static string pat_Run_Dist_meter {
            get {
                return ResourceManager.GetString("pat_Run_Dist_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run for ... hours per day 的當地語系化字串。
        /// </summary>
        public static string pat_Run_Dur_hours {
            get {
                return ResourceManager.GetString("pat_Run_Dur_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run for ... minutes per day 的當地語系化字串。
        /// </summary>
        public static string pat_Run_Dur_minutes {
            get {
                return ResourceManager.GetString("pat_Run_Dur_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Walk ... meter per day 的當地語系化字串。
        /// </summary>
        public static string pat_Walk_Dist_meter {
            get {
                return ResourceManager.GetString("pat_Walk_Dist_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Walk for ... hours per day 的當地語系化字串。
        /// </summary>
        public static string pat_Walk_Dur_hours {
            get {
                return ResourceManager.GetString("pat_Walk_Dur_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Walk for ... minutes per day 的當地語系化字串。
        /// </summary>
        public static string pat_Walk_Dur_minutes {
            get {
                return ResourceManager.GetString("pat_Walk_Dur_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Walk ... steps per day 的當地語系化字串。
        /// </summary>
        public static string pat_Walk_Steps {
            get {
                return ResourceManager.GetString("pat_Walk_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Challenge 的當地語系化字串。
        /// </summary>
        public static string pker_Challenge {
            get {
                return ResourceManager.GetString("pker_Challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Distance 的當地語系化字串。
        /// </summary>
        public static string pker_Dist {
            get {
                return ResourceManager.GetString("pker_Dist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duration 的當地語系化字串。
        /// </summary>
        public static string pker_Dur {
            get {
                return ResourceManager.GetString("pker_Dur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Normal 的當地語系化字串。
        /// </summary>
        public static string pker_Normal {
            get {
                return ResourceManager.GetString("pker_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Running 的當地語系化字串。
        /// </summary>
        public static string pker_Run {
            get {
                return ResourceManager.GetString("pker_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Steps 的當地語系化字串。
        /// </summary>
        public static string pker_Steps {
            get {
                return ResourceManager.GetString("pker_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Times 的當地語系化字串。
        /// </summary>
        public static string pker_Times {
            get {
                return ResourceManager.GetString("pker_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Walking 的當地語系化字串。
        /// </summary>
        public static string pker_Walk {
            get {
                return ResourceManager.GetString("pker_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done or not 的當地語系化字串。
        /// </summary>
        public static string pker_YesNo {
            get {
                return ResourceManager.GetString("pker_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string str_error {
            get {
                return ResourceManager.GetString("str_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Item 的當地語系化字串。
        /// </summary>
        public static string tbi_AddItem {
            get {
                return ResourceManager.GetString("tbi_AddItem", resourceCulture);
            }
        }
    }
}
